name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# permissions: {}
# contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      # Upload the generated build files
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-build
          path: target/*.war

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Test
        run: mvn test

  checkstyle:
    name: Checkstyle
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Checkstyle
        run: |
          mvn checkstyle:check || echo "Checkstyle violations found - continuing as warning"
